pub fn resolve_primitive(name: &str) -> Option<(u8, u8)> {
    match name {
        "add" => Some((0x00, 2)), "sub" => Some((0x01, 2)), "mul" => Some((0x02, 2)),
        "div" => Some((0x03, 2)), "mod" => Some((0x04, 2)),
        "neg" => Some((0x05, 1)), "abs" => Some((0x06, 1)),
        "min" => Some((0x07, 2)), "max" => Some((0x08, 2)), "pow" => Some((0x09, 2)),
        "bitand" => Some((0x10, 2)), "bitor" => Some((0x11, 2)),
        "bitxor" => Some((0x12, 2)), "bitnot" => Some((0x13, 1)),
        "shl" => Some((0x14, 2)), "shr" => Some((0x15, 2)),
        "eq" => Some((0x20, 2)), "ne" => Some((0x21, 2)),
        "lt" => Some((0x22, 2)), "gt" => Some((0x23, 2)),
        "le" => Some((0x24, 2)), "ge" => Some((0x25, 2)),
        "map" => Some((0x30, 2)), "filter" => Some((0x31, 2)), "zip" => Some((0x32, 2)),
        "int_to_float" => Some((0x40, 1)), "float_to_int" => Some((0x41, 1)),
        "float_to_bits" => Some((0x42, 1)), "bits_to_float" => Some((0x43, 1)),
        "bool_to_int" => Some((0x44, 1)),
        "self_graph" => Some((0x80, 0)),
        "graph_nodes" => Some((0x81, 1)),
        "graph_get_kind" => Some((0x82, 2)),
        "graph_get_prim_op" => Some((0x83, 2)),
        "graph_set_prim_op" => Some((0x84, 3)),
        "graph_add_node_rt" => Some((0x85, 2)),
        "graph_connect" => Some((0x86, 4)),
        "graph_connect_labeled" => Some((0xA5, 5)),
        "graph_disconnect" => Some((0x87, 3)),
        "graph_replace_subtree" => Some((0x88, 3)),
        "graph_eval" | "sg_eval" => Some((0x89, 2)),
        "graph_get_root" => Some((0x8A, 1)),
        "graph_add_guard_rt" => Some((0x8B, 4)),
        "graph_add_ref_rt" => Some((0x8C, 2)),
        "graph_set_cost" => Some((0x8D, 3)),
        "graph_get_lit_value" => Some((0x8E, 2)),
        "graph_outgoing" => Some((0x8F, 2)),
        "graph_get_node_cost" => Some((0x60, 2)),
        "graph_set_node_type" => Some((0x61, 3)),
        "graph_get_node_type" => Some((0x62, 2)),
        "graph_edges" => Some((0x63, 1)),
        "graph_get_arity" => Some((0x64, 2)),
        "graph_get_depth" => Some((0x65, 2)),
        "graph_get_lit_type_tag" => Some((0x66, 2)),
        // Parallel execution primitives (0x90-0x95)
        "par_eval" => Some((0x90, 1)),
        "par_map" => Some((0x91, 2)),
        "par_fold" => Some((0x92, 3)),
        "spawn" => Some((0x93, 1)),
        "await_future" => Some((0x94, 1)),
        "par_zip_with" => Some((0x95, 3)),
        // Knowledge graph primitives (0x70-0x7B)
        "kg_empty" => Some((0x70, 0)),
        "kg_add_node" => Some((0x71, 3)),
        "kg_add_edge" => Some((0x72, 5)),
        "kg_get_node" => Some((0x73, 2)),
        "kg_neighbors" => Some((0x75, 3)),
        "kg_set_edge_weight" => Some((0x76, 4)),
        "kg_map_nodes" => Some((0x77, 2)),
        "kg_merge" => Some((0x78, 2)),
        "kg_query_by_edge_type" => Some((0x79, 2)),
        "kg_node_count" => Some((0x7A, 1)),
        "kg_edge_count" => Some((0x7B, 1)),
        "graph_edge_count" => Some((0x96, 1)),
        "graph_get_opcode" => Some((0x83, 2)),  // alias for graph_get_prim_op
        "graph_edge_target" => Some((0x97, 4)),
        "graph_get_binder" => Some((0x98, 2)),
        "graph_eval_env" => Some((0x99, 3)),
        "graph_get_tag" => Some((0x9A, 2)),
        "graph_get_field_index" => Some((0x9B, 2)),
        "value_get_tag" => Some((0x9C, 1)),
        "value_get_payload" => Some((0x9D, 1)),
        "value_make_tagged" => Some((0x9E, 2)),
        "graph_get_effect_tag" => Some((0x9F, 2)),
        "state_empty" => Some((0x55, 0)),
        "state_get" => Some((0x50, 2)),
        "state_set" => Some((0x51, 3)),
        "evolve_subprogram" => Some((0xA0, 3)),
        "perform_effect" => Some((0xA1, 2)),
        "graph_eval_ref" => Some((0xA2, 3)),
        "compile_source_json" => Some((0xA3, 1)),
        "graph_set_binder" => Some((0xA4, 3)),
        "str_len" => Some((0xB0, 1)), "str_concat" => Some((0xB1, 2)),
        "str_slice" => Some((0xB2, 3)), "str_contains" => Some((0xB3, 2)),
        "str_split" => Some((0xB4, 2)), "str_join" => Some((0xB5, 2)),
        "str_to_int" => Some((0xB6, 1)), "int_to_string" => Some((0xB7, 1)),
        "str_eq" => Some((0xB8, 2)),
        "str_starts_with" => Some((0xB9, 2)), "str_ends_with" => Some((0xBA, 2)),
        "str_replace" => Some((0xBB, 3)), "str_trim" => Some((0xBC, 1)),
        "str_upper" => Some((0xBD, 1)), "str_lower" => Some((0xBE, 1)),
        "str_chars" => Some((0xBF, 1)), "char_at" => Some((0xC0, 2)),
        "list_append" => Some((0xC1, 2)), "list_nth" => Some((0xC2, 2)),
        "list_take" => Some((0xC3, 2)), "list_drop" => Some((0xC4, 2)),
        "list_sort" => Some((0xC5, 1)), "sort_by" => Some((0xCF, 2)), "list_dedup" => Some((0xC6, 1)),
        "list_range" => Some((0xC7, 2)), "list_concat" => Some((0xCE, 2)),
        "map_insert" => Some((0xC8, 3)), "map_get" => Some((0xC9, 2)),
        "map_remove" => Some((0xCA, 2)), "map_keys" => Some((0xCB, 1)),
        "map_values" => Some((0xCC, 1)), "map_size" => Some((0xCD, 1)),
        // Data access (0xD2, 0xD6)
        "tuple_get" => Some((0xD2, 2)),
        "tuple_len" => Some((0xD6, 1)),
        // String builder (0xD3-0xD5) — O(1) amortized append, avoids O(n²) str_concat in loops
        "buf_new" => Some((0xD3, 0)),
        "buf_push" => Some((0xD4, 2)),
        "buf_finish" => Some((0xD5, 1)),
        // Math (0xD8-0xE3)
        "math_sqrt" => Some((0xD8, 1)), "math_log" => Some((0xD9, 1)),
        "math_exp" => Some((0xDA, 1)), "math_sin" => Some((0xDB, 1)),
        "math_cos" => Some((0xDC, 1)), "math_floor" => Some((0xDD, 1)),
        "math_ceil" => Some((0xDE, 1)), "math_round" => Some((0xDF, 1)),
        "math_pi" => Some((0xE0, 0)), "math_e" => Some((0xE1, 0)),
        "random_int" => Some((0xE2, 2)), "random_float" => Some((0xE3, 0)),
        // Time (0xE4-0xE5)
        // Time (reserved — format/parse are pure IRIS in stdlib/time_ops.iris)
        // "time_format" and "time_parse" removed: they are string/math compositions
        // Bytes construction (0xE6-0xE8)
        "bytes_from_ints" => Some((0xE6, 1)),
        "bytes_concat" => Some((0xE7, 2)),
        "bytes_len" => Some((0xE8, 1)),
        // Lazy lists (0xE9-0xEC)
        "lazy_unfold" => Some((0xE9, 2)),
        "thunk_force" => Some((0xEA, 1)),
        "lazy_take" => Some((0xEB, 2)),
        "lazy_map" => Some((0xEC, 2)),
        "graph_new" => Some((0xED, 0)),
        "graph_set_root" => Some((0xEE, 2)),
        "graph_set_lit_value" => Some((0xEF, 4)),
        "list_len" => Some((0xF0, 1)),
        "graph_set_field_index" => Some((0xF1, 3)),
        // I/O substrate primitives (permanent — IRIS needs file access + compilation)
        "file_read" => Some((0xF2, 1)),
        "compile_source" => Some((0xF3, 1)),
        "debug_print" => Some((0xF4, 1)),  // substrate-level print (bypasses effect system)
        "module_eval" => Some((0xF5, 3)),
        "compile_test_file" => Some((0xF6, 2)),
        "module_test_count" => Some((0xF7, 1)),
        "module_eval_test" => Some((0xF8, 2)),
        _ => None,
    }
}

/// Returns the names of all known primitives.
pub fn primitive_names() -> &'static [&'static str] {
    &[
        "add", "sub", "mul", "div", "mod", "neg", "abs", "min", "max", "pow",
        "bitand", "bitor", "bitxor", "bitnot", "shl", "shr",
        "eq", "ne", "lt", "gt", "le", "ge",
        "map", "filter", "zip",
        "int_to_float", "float_to_int", "float_to_bits", "bits_to_float", "bool_to_int",
        "self_graph", "graph_nodes", "graph_get_kind", "graph_get_prim_op",
        "graph_set_prim_op", "graph_add_node_rt", "graph_connect", "graph_disconnect",
        "graph_replace_subtree", "graph_eval", "sg_eval", "graph_get_root",
        "graph_add_guard_rt", "graph_add_ref_rt", "graph_set_cost",
        "graph_get_lit_value", "graph_outgoing",
        "graph_get_node_cost", "graph_set_node_type", "graph_get_node_type",
        "graph_edges", "graph_get_arity", "graph_get_depth", "graph_get_lit_type_tag",
        "par_eval", "par_map", "par_fold", "spawn", "await_future", "par_zip_with",
        "kg_empty", "kg_add_node", "kg_add_edge", "kg_get_node", "kg_neighbors",
        "kg_set_edge_weight", "kg_map_nodes", "kg_merge", "kg_query_by_edge_type",
        "kg_node_count", "kg_edge_count",
        "graph_edge_count", "graph_get_opcode",
        "graph_edge_target", "graph_get_binder", "graph_eval_env",
        "graph_get_tag", "graph_get_field_index",
        "value_get_tag", "value_get_payload", "value_make_tagged", "graph_get_effect_tag",
        "state_empty", "state_get", "state_set",
        "evolve_subprogram", "perform_effect", "graph_eval_ref", "compile_source_json",
        "str_len", "str_concat", "str_slice", "str_contains", "str_split", "str_join",
        "str_to_int", "int_to_string", "str_eq", "str_starts_with", "str_ends_with",
        "str_replace", "str_trim", "str_upper", "str_lower", "str_chars", "char_at",
        "list_append", "list_nth", "list_take", "list_drop", "list_sort", "sort_by",
        "list_dedup", "list_range", "list_concat",
        "map_insert", "map_get", "map_remove", "map_keys", "map_values", "map_size",
        "tuple_get", "tuple_len",
        "math_sqrt", "math_log", "math_exp", "math_sin", "math_cos",
        "math_floor", "math_ceil", "math_round", "math_pi", "math_e",
        "random_int", "random_float",
        "bytes_from_ints", "bytes_concat", "bytes_len",
        "lazy_unfold", "thunk_force", "lazy_take", "lazy_map",
        "graph_new", "graph_set_root", "graph_set_lit_value",
        "list_len", "graph_set_field_index",
        "file_read", "compile_source", "debug_print",
        "module_eval", "compile_test_file", "module_test_count", "module_eval_test",
    ]
}
