
//! End-to-end self-hosting tests via pre-compiled JSON pipeline.
//!
//! Verifies that the full pipeline works through pre-compiled JSON files:
//!   source -> tokenize (JSON) -> parse (JSON) -> lower (JSON) -> evaluate
//!
//! The JSON files are generated by test_precompile_syntax.rs and live in bootstrap/.
//! The evaluation uses only iris-bootstrap (no iris-syntax at runtime).

use std::rc::Rc;

use iris_types::eval::Value;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Ensure the bootstrap JSON files exist by compiling them if needed.
fn ensure_precompiled() {
    let base = concat!(env!("CARGO_MANIFEST_DIR"), "/bootstrap");
    let tok_path = format!("{}/tokenizer.json", base);
    let parser_path = format!("{}/parser.json", base);
    let lowerer_path = format!("{}/lowerer.json", base);

    if !std::path::Path::new(&tok_path).exists()
        || !std::path::Path::new(&parser_path).exists()
        || !std::path::Path::new(&lowerer_path).exists()
    {
        compile_and_save_pipeline();
    }
}

fn compile_and_save_pipeline() {
    let base = concat!(env!("CARGO_MANIFEST_DIR"), "/bootstrap");

    for (src_name, out_name) in &[
        ("tokenizer.iris", "tokenizer.json"),
        ("iris_parser.iris", "parser.json"),
        ("iris_lowerer.iris", "lowerer.json"),
    ] {
        let src_path = format!(
            "{}/src/iris-programs/syntax/{}",
            env!("CARGO_MANIFEST_DIR"),
            src_name
        );
        let out_path = format!("{}/{}", base, out_name);
        let source = std::fs::read_to_string(&src_path)
            .unwrap_or_else(|e| panic!("Cannot read {}: {}", src_path, e));
        let result = iris_bootstrap::syntax::compile(&source);
        if !result.errors.is_empty() {
            for err in &result.errors {
                eprintln!("{}", iris_bootstrap::syntax::format_error(&source, err));
            }
            panic!("{} had {} compile errors", src_path, result.errors.len());
        }
        let graph = &result.fragments.last().unwrap().1.graph;
        iris_bootstrap::save_graph(graph, &out_path)
            .unwrap_or_else(|e| panic!("Cannot save {}: {}", out_path, e));
    }
}

/// Load the pre-compiled pipeline from JSON and run the full chain.
fn self_hosted_eval(source: &str, inputs: &[Value]) -> Value {
    ensure_precompiled();

    let base = concat!(env!("CARGO_MANIFEST_DIR"), "/bootstrap");

    let tokenizer = iris_bootstrap::load_graph(&format!("{}/tokenizer.json", base))
        .expect("failed to load tokenizer.json");
    let parser = iris_bootstrap::load_graph(&format!("{}/parser.json", base))
        .expect("failed to load parser.json");
    let lowerer = iris_bootstrap::load_graph(&format!("{}/lowerer.json", base))
        .expect("failed to load lowerer.json");

    // Step 1: Tokenize
    let tokens = iris_bootstrap::evaluate_with_limit(
        &tokenizer,
        &[Value::String(source.to_string())],
        5_000_000,
    )
    .expect("tokenizer failed");

    // Step 2: Parse
    let ast = iris_bootstrap::evaluate_with_limit(
        &parser,
        &[tokens, Value::String(source.to_string())],
        50_000_000,
    )
    .expect("parser failed");

    // Step 3: Lower
    let program = iris_bootstrap::evaluate_with_limit(
        &lowerer,
        &[ast, Value::String(source.to_string())],
        50_000_000,
    )
    .expect("lowerer failed");

    // Step 4: Extract SemanticGraph (handles both Program and Tuple(Program, smap))
    let graph = match program {
        Value::Program(g) => Rc::try_unwrap(g).unwrap_or_else(|rc| (*rc).clone()),
        Value::Tuple(ref fields) if !fields.is_empty() => {
            match &fields[0] {
                Value::Program(g) => g.as_ref().clone(),
                _ => panic!("lowerer tuple[0] should be Program, got {:?}", fields[0]),
            }
        }
        other => panic!("lowerer returned {:?}, expected Program", other),
    };

    // Step 5: Evaluate
    iris_bootstrap::evaluate_with_limit(&graph, inputs, 5_000_000)
        .expect("evaluation failed")
}

// ---------------------------------------------------------------------------
// JSON round-trip verification
// ---------------------------------------------------------------------------

#[test]
fn test_e2e_json_roundtrip() {
    ensure_precompiled();

    let base = concat!(env!("CARGO_MANIFEST_DIR"), "/bootstrap");

    for name in &["tokenizer.json", "parser.json", "lowerer.json"] {
        let path = format!("{}/{}", base, name);
        let graph = iris_bootstrap::load_graph(&path)
            .unwrap_or_else(|e| panic!("failed to load {}: {}", path, e));
        assert!(
            !graph.nodes.is_empty(),
            "{} should have nodes",
            name
        );
        assert!(
            graph.nodes.contains_key(&graph.root),
            "{} root should be in nodes",
            name
        );

        // Re-save and re-load to verify full round-trip
        let tmp = format!("/tmp/iris_roundtrip_{}", name);
        iris_bootstrap::save_graph(&graph, &tmp)
            .unwrap_or_else(|e| panic!("failed to save {}: {}", tmp, e));
        let reloaded = iris_bootstrap::load_graph(&tmp)
            .unwrap_or_else(|e| panic!("failed to reload {}: {}", tmp, e));
        assert_eq!(
            reloaded.root, graph.root,
            "{} root mismatch after round-trip",
            name
        );
        assert_eq!(
            reloaded.nodes.len(),
            graph.nodes.len(),
            "{} node count mismatch after round-trip",
            name
        );
        let _ = std::fs::remove_file(&tmp);
    }
}

// ---------------------------------------------------------------------------
// End-to-end tests: source -> JSON pipeline -> evaluate
// ---------------------------------------------------------------------------

#[test]
fn test_e2e_constant() {
    let result = self_hosted_eval("let c = 42", &[]);
    assert_eq!(result, Value::Int(42), "constant 42");
}

#[test]
fn test_e2e_identity() {
    let result = self_hosted_eval("let id x = x", &[Value::Int(7)]);
    assert_eq!(result, Value::Int(7), "identity(7)");
}

#[test]
fn test_e2e_addition() {
    let result = self_hosted_eval("let add x y = x + y", &[Value::Int(3), Value::Int(5)]);
    assert_eq!(result, Value::Int(8), "add(3, 5)");
}

#[test]
fn test_e2e_subtraction() {
    let result = self_hosted_eval("let sub x y = x - y", &[Value::Int(10), Value::Int(3)]);
    assert_eq!(result, Value::Int(7), "sub(10, 3)");
}

#[test]
fn test_e2e_multiplication() {
    let result = self_hosted_eval("let mul x y = x * y", &[Value::Int(6), Value::Int(7)]);
    assert_eq!(result, Value::Int(42), "mul(6, 7)");
}

#[test]
fn test_e2e_guard() {
    let result_neg = self_hosted_eval(
        "let abs x = if x < 0 then 0 - x else x",
        &[Value::Int(-5)],
    );
    assert_eq!(result_neg, Value::Int(5), "abs(-5)");

    let result_pos = self_hosted_eval(
        "let abs x = if x < 0 then 0 - x else x",
        &[Value::Int(3)],
    );
    assert_eq!(result_pos, Value::Int(3), "abs(3)");
}

#[test]
fn test_e2e_nested_arithmetic() {
    let result = self_hosted_eval("let f x = (x + 1) * (x - 1)", &[Value::Int(5)]);
    assert_eq!(result, Value::Int(24), "(5+1)*(5-1)");
}

#[test]
fn test_e2e_let_binding() {
    let result = self_hosted_eval("let f x = let y = x + 1 in y * 2", &[Value::Int(3)]);
    assert_eq!(result, Value::Int(8), "let y = 3+1 in y*2");
}

#[test]
fn test_e2e_comparison() {
    let result1 = self_hosted_eval(
        "let mx x y = if x > y then x else y",
        &[Value::Int(3), Value::Int(7)],
    );
    assert_eq!(result1, Value::Int(7), "max(3, 7)");

    let result2 = self_hosted_eval(
        "let mx x y = if x > y then x else y",
        &[Value::Int(10), Value::Int(2)],
    );
    assert_eq!(result2, Value::Int(10), "max(10, 2)");
}

#[test]
fn test_e2e_boolean_true() {
    let result = self_hosted_eval("let t = true", &[]);
    assert_eq!(result, Value::Bool(true), "true literal");
}

#[test]
fn test_e2e_boolean_false() {
    let result = self_hosted_eval("let f = false", &[]);
    assert_eq!(result, Value::Bool(false), "false literal");
}

#[test]
fn test_e2e_unary_neg() {
    let result = self_hosted_eval("let f x = 0 - x", &[Value::Int(5)]);
    assert_eq!(result, Value::Int(-5), "0 - 5 = -5");
}

#[test]
fn test_e2e_multi_param() {
    let result = self_hosted_eval(
        "let f x y z = x + y + z",
        &[Value::Int(1), Value::Int(2), Value::Int(3)],
    );
    assert_eq!(result, Value::Int(6), "1+2+3");
}

#[test]
fn test_e2e_nested_if() {
    let result_low = self_hosted_eval(
        "let clamp x lo hi = if x < lo then lo else if x > hi then hi else x",
        &[Value::Int(-5), Value::Int(0), Value::Int(100)],
    );
    assert_eq!(result_low, Value::Int(0), "clamp(-5, 0, 100)");

    let result_high = self_hosted_eval(
        "let clamp x lo hi = if x < lo then lo else if x > hi then hi else x",
        &[Value::Int(200), Value::Int(0), Value::Int(100)],
    );
    assert_eq!(result_high, Value::Int(100), "clamp(200, 0, 100)");

    let result_mid = self_hosted_eval(
        "let clamp x lo hi = if x < lo then lo else if x > hi then hi else x",
        &[Value::Int(50), Value::Int(0), Value::Int(100)],
    );
    assert_eq!(result_mid, Value::Int(50), "clamp(50, 0, 100)");
}

#[test]
fn test_e2e_eq_comparison() {
    let result1 = self_hosted_eval(
        "let is_zero x = if x == 0 then 1 else 0",
        &[Value::Int(0)],
    );
    assert_eq!(result1, Value::Int(1), "is_zero(0)");

    let result2 = self_hosted_eval(
        "let is_zero x = if x == 0 then 1 else 0",
        &[Value::Int(5)],
    );
    assert_eq!(result2, Value::Int(0), "is_zero(5)");
}

#[test]
fn test_e2e_le_comparison() {
    let result1 = self_hosted_eval(
        "let is_small x = if x <= 10 then 1 else 0",
        &[Value::Int(5)],
    );
    assert_eq!(result1, Value::Int(1), "is_small(5)");

    let result2 = self_hosted_eval(
        "let is_small x = if x <= 10 then 1 else 0",
        &[Value::Int(10)],
    );
    assert_eq!(result2, Value::Int(1), "is_small(10)");

    let result3 = self_hosted_eval(
        "let is_small x = if x <= 10 then 1 else 0",
        &[Value::Int(11)],
    );
    assert_eq!(result3, Value::Int(0), "is_small(11)");
}
